### ISSUE TITLE
How Fix This

### ISSUE THREAD

**Issue by isuruwa** [railwayapp/starters#161]
End of The Line
You've been flagged for violations concerning the Railway ToS. The reason specified is "Crypto miner".
If you believe this is in error; please reach out on the Discord and we'll get you sorted!
This process is automated, new, and in constant evolution. Apologies for any inconvenience.

**Comment by coffee-cup** [comment]
Hey @isuruwa . Can you please reach out to one of the team on [Discord](https://discord.gg/xAm2w6g)
