### ISSUE TITLE
Calendso starter doesn’t work

### ISSUE THREAD

**Issue by Rohithgilla12** [railwayapp/starters#170]
I have tried to deploy it normally it didn’t work, on further digging I found out about this issue 
https://github.com/calendso/calendso/pull/393

I tried adding it into my code and ran the build, still same error.

**Comment by olui1** [comment]
Yeah I'm currently facing the same issue. I wonder if anything can be done with the react-dates dependency.

**Comment by Rohithgilla12** [comment]
https://github.com/calendso/calendso/pull/393 got merged and this is working now.

Refer to the image below to verify it is working.

<img width="804" alt="Screenshot 2021-08-24 at 10 34 25 AM" src="https://user-images.githubusercontent.com/19389850/130558766-e1681d37-b133-4e9a-8a67-8c212e978e5a.png">


Thanks and closing the issue.
