### ISSUE TITLE
Broken rails-starter when deploying from railway.app

### ISSUE THREAD

**Issue by wzulfikar** [railwayapp/starters#77]
I was trying to deploy rails app using railway.app ui and so I chose [rails-starter](https://github.com/railwayapp/starters/tree/master/examples/rails-starter). However, the build was broken because of `mimemagic`:

<img width="500" src="https://user-images.githubusercontent.com/7823011/115957015-a29bcf00-a532-11eb-9d1b-a175c2fdf9ac.png" />

To fix this, I had to: 
1. Clone the repo to my github
2. [Regenerate Gemfile.lock](https://github.com/wzulfikar/rails-on-rail/commit/584bdd391903dbe52c0d75b44a54ba79229877c6
) (delete the Gemfile.lock and run `bundle install`)
3. Deploy to railway again

Maybe it would be good if we fix the issue in Gemfile.lock in [rails-starter template](https://github.com/railwayapp/starters/tree/master/examples/rails-starter) so that future deployments won't break? I just think that it's a bit bummer to onboard new developers and then faced with build error.

**Comment by coffee-cup** [comment]
Thanks for the report @wzulfikar. It should definitely be fixed!
